package com.edu.bidlab.weshareiotservice.dao;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_manufacturer
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private String productManufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.fk_category_id
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private Byte fkCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.variable
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private String variable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_publish
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private Byte isPublish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_manufacturer
     *
     * @return the value of product.product_manufacturer
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public String getProductManufacturer() {
        return productManufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_manufacturer
     *
     * @param productManufacturer the value for product.product_manufacturer
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setProductManufacturer(String productManufacturer) {
        this.productManufacturer = productManufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type
     *
     * @return the value of product.product_type
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type
     *
     * @param productType the value for product.product_type
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.fk_category_id
     *
     * @return the value of product.fk_category_id
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public Byte getFkCategoryId() {
        return fkCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.fk_category_id
     *
     * @param fkCategoryId the value for product.fk_category_id
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setFkCategoryId(Byte fkCategoryId) {
        this.fkCategoryId = fkCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.variable
     *
     * @return the value of product.variable
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public String getVariable() {
        return variable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.variable
     *
     * @param variable the value for product.variable
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setVariable(String variable) {
        this.variable = variable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_publish
     *
     * @return the value of product.is_publish
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public Byte getIsPublish() {
        return isPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_publish
     *
     * @param isPublish the value for product.is_publish
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setIsPublish(Byte isPublish) {
        this.isPublish = isPublish;
    }
}