package com.edu.bidlab.weshareiotservice.dao;

public class Variable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column variable.id
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column variable.variable_name
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private String variableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column variable.variable_identification
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private String variableIdentification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column variable.data_type
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private Byte dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column variable.unit
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private Byte unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column variable.rw_type
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private Byte rwType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column variable.necessary
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private Byte necessary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column variable.discription
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    private String discription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column variable.id
     *
     * @return the value of variable.id
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column variable.id
     *
     * @param id the value for variable.id
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column variable.variable_name
     *
     * @return the value of variable.variable_name
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public String getVariableName() {
        return variableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column variable.variable_name
     *
     * @param variableName the value for variable.variable_name
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setVariableName(String variableName) {
        this.variableName = variableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column variable.variable_identification
     *
     * @return the value of variable.variable_identification
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public String getVariableIdentification() {
        return variableIdentification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column variable.variable_identification
     *
     * @param variableIdentification the value for variable.variable_identification
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setVariableIdentification(String variableIdentification) {
        this.variableIdentification = variableIdentification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column variable.data_type
     *
     * @return the value of variable.data_type
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public Byte getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column variable.data_type
     *
     * @param dataType the value for variable.data_type
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setDataType(Byte dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column variable.unit
     *
     * @return the value of variable.unit
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public Byte getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column variable.unit
     *
     * @param unit the value for variable.unit
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setUnit(Byte unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column variable.rw_type
     *
     * @return the value of variable.rw_type
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public Byte getRwType() {
        return rwType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column variable.rw_type
     *
     * @param rwType the value for variable.rw_type
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setRwType(Byte rwType) {
        this.rwType = rwType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column variable.necessary
     *
     * @return the value of variable.necessary
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public Byte getNecessary() {
        return necessary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column variable.necessary
     *
     * @param necessary the value for variable.necessary
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setNecessary(Byte necessary) {
        this.necessary = necessary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column variable.discription
     *
     * @return the value of variable.discription
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column variable.discription
     *
     * @param discription the value for variable.discription
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    public void setDiscription(String discription) {
        this.discription = discription;
    }
}