package com.edu.bidlab.weshareiotservice.mapper;

import com.edu.bidlab.weshareiotservice.dao.Variable;

public interface VariableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    int insert(Variable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    int insertSelective(Variable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    Variable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    int updateByPrimaryKeySelective(Variable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbggenerated Tue Apr 07 10:36:47 CST 2020
     */
    int updateByPrimaryKey(Variable record);
}